server:
  servlet:
    port: 8090
    contextPath: /api

spring:

  application:
    name: quora-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quora
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect